.*Assembler messages:
.*Error: cannot find default versions of the ISA extension `l'
.*Error: cannot find default versions of the ISA extension `n'
.*Warning: -march=rv32iln_zicsr_xargle_xbargle: unknown x ISA extension `xargle'
.*Error: x ISA extension `xargle' must be set with the versions
.*Warning: -march=rv32iln_zicsr_xargle_xbargle: unknown x ISA extension `xbargle'
.*Error: x ISA extension `xbargle' must be set with the versions
